import { HttpStatus } from '@nestjs/common';

export const StatusCodeEnum = {
  ...HttpStatus,
  ALREADY_EXIST: 600,
  INVALID_PASSWORD: 601,
  MISSING_JWT_SECRET: 602,
  BAD_CREDENTIALS: 603,
  ALREADY_VERIFIED: 604,
  INVALID_VERIFICATION_CODE: 605,
  COMPANY_NOT_FOUND: 606,
  COMPANY_USER_NOT_FOUND: 607,
  MOCK_NOT_FOUND: 608,
};
